### ISSUE TITLE
[FEATURE_REQUEST] Sign source code with cosign too

### ISSUE THREAD

**Issue by kpcyrd** [stackrox/kube-linter#336]
hi! I noticed cosign was introduced in #295 and I'm trying to verify the signature in the [Arch Linux package](https://archlinux.org/packages/community/x86_64/kube-linter/), but I can't find a signature for the source code .tar.gz.

```
% cosign verify-blob --key cosign.pub kube-linter-0.3.0.tar.gz                        
Error: verifying blob [kube-linter-0.3.0.tar.gz]: missing flag '--signature'
main.go:52: error during command execution: verifying blob [kube-linter-0.3.0.tar.gz]: missing flag '--signature'
```

Could this be added too?

**Comment by janisz** [comment]
https://github.com/stackrox/kube-linter/pull/338
